### ISSUE TITLE
Python 3.7 install support

### ISSUE THREAD

**Issue by djsiroky** [Esri/pyprt#11]
Hi there, thanks for releasing this Python library for CityEngine!

While the documentation says pyprt is compatible with `Python >=3.6`, attempting to install it on Python 3.7 doesn't work.

![image](https://user-images.githubusercontent.com/11220250/75466247-8791f700-594f-11ea-8b30-c135e9a2d4bd.png)

I'm not 100%, but I believe it may be due to specifying an explicit Python version for the files on PyPI:
![image](https://user-images.githubusercontent.com/11220250/75466464-da6bae80-594f-11ea-9f5e-31ab487a1bfb.png)

Not major, but may save users some confusion to either tweak the README to specify 3.6 only or somehow allow those .whl files to include 3.7+ as well. Cheers.

**Comment by mistafunk** [comment]
Thanks for the feedback, we'll clarify the docs asap (what we meant is that building it with Py >= 3.6 is supported). We hope to provide pre-built wheels for more Python versions eventually.

**Comment by clechot** [comment]
(Part of internal ticket CE-7604.)

**Comment by mistafunk** [comment]
Added a small clarification for v1.0.0
