### ISSUE TITLE
Street Support & GP Framework

### ISSUE THREAD

**Issue by d-wasserman** [Esri/pyprt#12]
Hi @clechot , 

Great work so far! Big question I have. 
1. Can this work within the Esri GP Framework or can it work outside of it? The GP Tool Framework already has basic support for [supporting procedural model generation](https://pro.arcgis.com/en/pro-app/tool-reference/3d-analyst/layer-3d-to-feature-class.htm) through some odd hacks. This is however hard to make live. Can this be used with a server side GP service in a 3D app? 
2. I take it this does not support streets native in CityEngine, but requires a base shape geometry typical from polygon formats? Confirmation requested. 

Thanks, 

David

**Comment by clechot** [comment]
Hi David,

Thanks for your questions.

1. I haven't tested it myself but it should work as well in Esri GP framework and in a server side app. It works outside of it of course.
2. I confirm.

Camille

**Comment by d-wasserman** [comment]
Thanks. I hope to test this out when  I can find time.
