### ISSUE TITLE
Allow combined use of PyEncoder and builtin encoders for print, reports and errors

### ISSUE THREAD

**Issue by mistafunk** [Esri/pyprt#37]
It is currently not possible to use the PyEncoder in combination with e.g. the CGA print encoder  because of the hard distinction between "use PyEncoder/PyCallbacks" vs "use built-in encoders of PRT with file output callbacks).

Tasks:
1. Always add the print, report and error encoders provided by PRT
1. Ensure handling the callbacks of above encoders in the PyCallbacks
1. Cleanup the code to prevent the multiple "if encoder == PyEncoder" distinctions

**Comment by clechot** [comment]
(Internal ticket: CE-8088)

**Comment by mistafunk** [comment]
merged & verified.
