### ISSUE TITLE
compiling python 3.7 wheel under Windows 10

### ISSUE THREAD

**Issue by davethejoy** [Esri/pyprt#41]
I am attempting to generate a python 3.7 wheel file, and I getting errors

- I am running within a conda 3.7 environment with pipenv installed

`(base) C:\Users\dave.lajoie\Documents\dev\pyprt>pipenv --python 3.7 install
Virtualenv already exists!
Removing existing virtualenv…
Creating a virtualenv for this project…
Pipfile: C:\Users\dave.lajoie\Documents\dev\pyprt\Pipfile
Using c:/users/dave.lajoie/miniconda3/python.exe (3.7.6) to create virtualenv…
[ ===] Creating virtual environment...Already using interpreter c:\users\dave.lajoie\miniconda3\python.exe
Using base prefix 'c:\\users\\dave.lajoie\\miniconda3'
New python executable in C:\Users\dave.lajoie\.virtualenvs\pyprt-2N8YQA4C\Scripts\python.exe
copying c:\users\dave.lajoie\miniconda3\python.exe => C:\Users\dave.lajoie\.virtualenvs\pyprt-2N8YQA4C\Scripts\python.exe
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter c:/users/dave.lajoie/miniconda3/python.exe

Successfully created virtual environment!
Virtualenv location: C:\Users\dave.lajoie\.virtualenvs\pyprt-2N8YQA4C
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
 Locking...Building requirements...
Resolving dependencies...
Success!
Updated Pipfile.lock (7214ea)!
Installing dependencies from Pipfile.lock (7214ea)…
An error occurred while installing requests==2.23.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4' --hash=sha256:b3f43d496c6daba4493e7c431722aeb7dbc6288f52a6e04e7b6023b0247817e6 --hash=sha256:43999036bfa82904b6af1d99e4882b560e5e2c68e5c4b0aa03b655f3d7d73fee! Will try again.
  ================================ 89/89 - 00:02:16
Installing initially failed dependencies…
     ================================ 1/1 - 00:00:01
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

(base) C:\Users\dave.lajoie\Documents\dev\pyprt>pipenv run python setup.py bdist_wheel
c:\users\dave.lajoie\miniconda3\Lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'distclass'
  warnings.warn(msg)
c:\users\dave.lajoie\miniconda3\Lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'conda_import_tests'
  warnings.warn(msg)
running bdist_wheel
running build
running build_py
running egg_info
writing PyPRT.egg-info\PKG-INFO
writing dependency_links to PyPRT.egg-info\dependency_links.txt
writing top-level names to PyPRT.egg-info\top_level.txt
reading manifest file 'PyPRT.egg-info\SOURCES.txt'
writing manifest file 'PyPRT.egg-info\SOURCES.txt'
warning: build_py: byte-compiling is disabled, skipping.

running build_ext
Configuring CMake project
CMake Configuration:
    cmake           : cmake
    cmake generator : Ninja
    make            : ninja
C:\Users\dave.lajoie\Miniconda3\Library\bin\cmake.exe -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=build\lib.win-amd64-3.7\pyprt\pyprt -DPYTHON_EXECUTABLE=C:\Users\dave.lajoie\.virtualenvs\pyprt-2N8YQA4C\Scripts\python.exe -Hsrc -Bbuild\temp.win-amd64-3.7\Release -GNinja -DCMAKE_MAKE_PROGRAM=ninja
-- The CXX compiler identification is MSVC 19.26.28806.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x86/cl.exe - broken
CMake Error at C:/Users/dave.lajoie/Miniconda3/Library/share/cmake-3.17/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/dave.lajoie/Documents/dev/pyprt/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeTmp

    Run Build Command(s):ninja cmTC_fc459 && [1/2] Building CXX object CMakeFiles\cmTC_fc459.dir\testCXXCompiler.cxx.obj
    [2/2] Linking CXX executable cmTC_fc459.exe
    FAILED: cmTC_fc459.exe
    cmd.exe /C "cd . && C:\Users\dave.lajoie\Miniconda3\Library\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_fc459.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\BUILDT~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x86\link.exe /nologo CMakeFiles\cmTC_fc459.dir\testCXXCompiler.cxx.obj  /out:cmTC_fc459.exe /implib:cmTC_fc459.lib /pdb:cmTC_fc459.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    LINK Pass 1: command "C:\PROGRA~2\MICROS~1\2019\BUILDT~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x86\link.exe /nologo CMakeFiles\cmTC_fc459.dir\testCXXCompiler.cxx.obj /out:cmTC_fc459.exe /implib:cmTC_fc459.lib /pdb:cmTC_fc459.pdb /version:0.0 /machine:X86 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_fc459.dir/intermediate.manifest CMakeFiles\cmTC_fc459.dir/manifest.res" failed (exit code 1104) with the following output:
    LINK : fatal error LNK1104: cannot open file 'kernel32.lib'
    ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:22 (project)

-- Configuring incomplete, errors occurred!
See also "C:/Users/dave.lajoie/Documents/dev/pyprt/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log".
See also "C:/Users/dave.lajoie/Documents/dev/pyprt/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeError.log".
error: command 'C:\\Users\\dave.lajoie\\Miniconda3\\Library\\bin\\cmake.exe' failed with exit status 1` 
any help would be appreciated.
tx

**Comment by mistafunk** [comment]
Hi Dave,

we believe the error is caused by the active conda environment indicated by the "(base)" prefix of your original pipenv command.

Please avoid mixing these two "world" by calling the pipenv commands for building the wheel in a standard windows visual studio command shell. Maybe you need to deactivate conda for that.

**Comment by davethejoy** [comment]
My bad, conda python is the only python installed locally. I will install a vanilla python so I can get the right setup. tx for pointing this out.

**Comment by davethejoy** [comment]
I deactivated my conda env, and installed a vanilla python 3.7 for windows.

`C:\Users\dave.lajoie\Documents\dev\pyprt>C:\Users\dave.lajoie\AppData\Local\Programs\Python\Python37\Scripts\pipenv.exe install
Installing dependencies from Pipfile.lock (7214ea)…
  ================================ 0/0 - 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

C:\Users\dave.lajoie\Documents\dev\pyprt>C:\Users\dave.lajoie\AppData\Local\Programs\Python\Python37\Scripts\pipenv.exe run C:\Users\dave.lajoie\AppData\Local\Programs\Python\Python37\python.exe setup.py bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    from sphinx.setup_command import BuildDoc
ModuleNotFoundError: No module named 'sphinx'`

**Comment by davethejoy** [comment]
got it to work, sphinx was missing in the environment
Here is my installation steps:

`1) Make sure no conda environment is active
> conda deactivate

2) Install Python 3.7 Vanilla on your system.
Depending on your installation configuration, python could have been installed in your home account or for all local user account.
Make sure to uppdate the command line below to reflect your installation
For the sake of clarify, we are assuming here the Python was installed under the user home account.
%USERPROFILE%\AppData\Local\Programs\Python\Python37\python.exe

3) upgrade pip
> %USERPROFILE%\AppData\Local\Programs\Python\Python37\Scripts\pip.exe install pip --upgrade

4) pip install pipenv
> %USERPROFILE%\AppData\Local\Programs\Python\Python37\Scripts\pip.exe install pipenv

5) pip install sphinx
> %USERPROFILE%\AppData\Local\Programs\Python\Python37\Scripts\pip.exe install sphinx

6) Clone PyPRT git repo
> cd <development directory>
> git clone https://github.com/Esri/pyprt.git
> cd pyprt

7) Add visual studio env vars
> "c:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars32.bat" amd64

8) Install pipenv
> %USERPROFILE%\AppData\Local\Programs\Python\Python37\Scripts\pipenv.exe install --skip-lock

9) Run pipenv build command
> %USERPROFILE%\AppData\Local\Programs\Python\Python37\Scripts\pipenv.exe run python setup.py bdist_wheel`

**Comment by davethejoy** [comment]
closing

**Comment by clechot** [comment]
The step number 5 is not necessary. Sphinx should be installed when creating the virtual environment (see Pipfile).
