### ISSUE TITLE
'streetWidth' always returned by 'inspect_rpk' method

### ISSUE THREAD

**Issue by brysonmarazzi** [Esri/pyprt#60]
The method `inspect_rpk` returns a dict that always contains `streetWidth` even when the input rpk file does not reference `streetwidth`. 

To reproduce this bug, run the `inspect_rpk` method with the file `noRule.rpk` from [here](https://github.com/Esri/pyprt-examples/blob/master/data/noRule.rpk). The output is `{'streetWidth': 'float'}` but there should be no CGA attributes returns (i.e empty JSON string), as the input rule file doesn't contain any rules.

**Comment by clechot** [comment]
Hello,
Thanks for your feedback. Concerning the `streetWidth` attribute, this attribute is indeed listed because it's inherent to all RPKs (it's needed for some CGA operations). But you're right, this default attribute can be and will be filtered out in the next PyPRT version.
