### ISSUE TITLE
InitialShape with holes

### ISSUE THREAD

**Issue by tramka** [Esri/pyprt#66]
Hi,

I am trying to create 3D files from feature class stored on ArcGIS Online. I am able to get a data using ArcGIS API for Python. 

Everything is working well until the moment, when I have a polygon with a hole. I am getting back a statement that the feature is not valid. I checked the code in function **arcgis_to_pyprt** and the problem is inside. According to the documentation, function expect a polygon without any hole.

The initial polygon with a hole looks like this:

`{"geometry": {"hasZ": true, "rings": [[[-604202.618999999, -1162026.378, 0], [-604199.545000002, -1162028.832, 0], [-604200.589000002, -1162029.938, 0], [-604206.98, -1162036.167, 0], [-604207.879999999, -1162035.177, 0], [-604211.749000002, -1162037.998, 0], [-604216.719000001, -1162031.849, 0], [-604208.859000001, -1162021.407, 0], [-604202.618999999, -1162026.378, 0], [-604202.618999999, -1162026.378, 0]], [[-604208.579999998, -1162029.887, 0], [-604205.230999999, -1162032.567, 0], [-604202.931000002, -1162029.697, 0], [-604206.296, -1162027.024, 0], [-604208.579999998, -1162029.887, 0], [-604208.579999998, -1162029.887, 0]]]}, "attributes": {"OBJECTID":  115345}}`

It seems the geometry has to be remade to following constructor:
`__init__ (vert_coordinates, face_indices, face_count, holes)`

However, I realized another problem. When I tried to create an object with a hole using this constructor, I am able to import the result to CE, but when I try to create a multipatch from it using the tool Import 3D Files (from Collada file), I am getting an error 050038: No Valid Files.

Thank you.

**Comment by mistafunk** [comment]
Thanks for your feedback. We are very close to releasing PyPRT 1.2 which includes https://github.com/Esri/pyprt/pull/58. If I understand correctly this should fix your first issue.

Can you provide more info about the second issue?

**Comment by tramka** [comment]
Amazing. Yes, it should fix the issue. 

The second issue:
When I was exploring the documentation about initial shapes with holes (btw. which is not very clear in my opinion - it took me a while to understand the meaning of parameters), I tried to create a polygon with a hole from an example in documentation.

```
shape_with_hole = pyprt.InitialShape([0, 0, 0, 0, 0, 10, 10, 0, 10, 10, 0, 0, 2, 0, 2, 8, 0, 8, 2, 0, 8], 
                                     [0, 1, 2, 3, 4, 5, 6], 
                                     [4, 3], 
                                     [[0, 1]])

m = pyprt.ModelGenerator([shape_with_hole])
rpk = os.path.join(r'Z:\GIS\pyprt-examples-master\data', 'extrusion_rule.rpk')
attrs = {'shapeName': 'myShape', 'seed': 555}
encoder_options = {'outputPath': r'Z:\GIS'}
os.makedirs(encoder_options['outputPath'], exist_ok=True)

models = m.generate_model([attrs], rpk, 'com.esri.prt.codecs.ColladaEncoder', encoder_options)
print('\nGenerated models located in '+encoder_options['outputPath'])
```

The output seems okay - `Generated models located in Z:\GIS`

The result in CE looks fine. 
![shape_hole](https://user-images.githubusercontent.com/37137459/100414772-d1dd0b80-307a-11eb-8b5b-a16e7ea07828.PNG)

However, when I try to create a multipatch from generated model using Import 3d files in GIS, I am getting an error:
```
inFile = r"Z:\GIS\base_name_0.dae"
outFile = r"Z:\Test.gdb\Multipatch_from_PYPRT"
arcpy.ddd.Import3DFiles(inFile, outFile, "ONE_ROOT_ONE_FEATURE", None, "Z_IS_UP", "DAE", None, None)
```
I am getting an error:
```
---------------------------------------------------------------------------
ExecuteError                              Traceback (most recent call last)
<ipython-input-11-8b81c9f965b7> in <module>
      6                         "*",
      7                         None,
----> 8                         None)

C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\ddd.py in Import3DFiles(in_files, out_featureClass, root_per_feature, spatial_reference, y_is_up, file_suffix, in_featureClass, symbol_field)
    800         return retval
    801     except Exception as e:
--> 802         raise e
    803 
    804 @gptooldoc('Layer3DToFeatureClass_3d', None)

C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\ddd.py in Import3DFiles(in_files, out_featureClass, root_per_feature, spatial_reference, y_is_up, file_suffix, in_featureClass, symbol_field)
    797     from arcpy.arcobjects.arcobjectconversion import convertArcObjectToPythonObject
    798     try:
--> 799         retval = convertArcObjectToPythonObject(gp.Import3DFiles_3d(*gp_fixargs((in_files, out_featureClass, root_per_feature, spatial_reference, y_is_up, file_suffix, in_featureClass, symbol_field), True)))
    800         return retval
    801     except Exception as e:

C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py in <lambda>(*args)
    509         val = getattr(self._gp, attr)
    510         if callable(val):
--> 511             return lambda *args: val(*gp_fixargs(args, True))
    512         else:
    513             return convertArcObjectToPythonObject(val)

ExecuteError: ERROR 050038: No Valid Files
ERROR 050038: No Valid Files
Failed to execute (Import3DFiles).
```

When I tried to open COLLADA file using Quick Import in Data Interoperability, I have got only table with a warning (no multipatch was generated):

```
A 3D feature was encountered in the feature class 'base_name_0_geom', which is defined as containing 2D features. The feature, and any other applicable features in the same feature class, will be modified so that it has the same dimension as the feature class
```

So, if my thoughts are right, it is maybe not an issue of the module, but the problem is inside of ArcGIS. If so, you can close an issue and thank you for your time!
