### ISSUE TITLE
Roof orientation

### ISSUE THREAD

**Issue by tramka** [Esri/pyprt#67]
Hi,

maybe I discovered another issue. I tried to export COLLADA files from ArcGIS Online and visualize them in CE. Works perfect. But when I create a 3D model using RulePackage directly in CE, I am getting different roof orientation at some buildings. How is it possible? I am using the same rule package for the both workflows. The key attribute for roof direction is called **RoofDirAdjust**.

**The workflow 1 - generating model from AGOL:**
Structure of features:
```
{"geometry": {"hasZ": true, "rings": [[[-604818.02, -1161730.147, 0], [-604819.489999998, -1161731.437, 0], [-604822.739, -1161727.588, 0], [-604821.09, -1161726.177, 0], [-604820.350000001, -1161725.547, 0], [-604817.107000001, -1161729.343, 0], [-604818.02, -1161730.147, 0], [-604818.02, -1161730.147, 0]]]}, "attributes": {"OBJECTID": 178, "FID_BLD_part": 178, "KU_KOD": 608505, "ROOFFORM": "Gable", "ROOFDIR": null, "RoofDirAdjust": 0, "BASEELEVATION": 266.04, "BLDGHEIGHT": 4.30500000000001, "EAVEHEIGHT": 2.5}
```
The rule package contains the attributes:
```
pyprt.inspect_rpk(rpk)

{'streetWidth': 'float',
 'BASEELEVATION': 'float',
 'BLDGHEIGHT': 'float',
 'EAVEHEIGHT': 'float',
 'FloorLineColor': 'string',
 'MansardAngle': 'float',
 'ROOFFORM': 'string',
 'RoofColor': 'string',
 'RoofDirAdjust': 'float',
 'RoofPitchAngle': 'float',
 'WallColor': 'string'}
```

I prepare variable attrs and output looks fine (example of one dict in list):
`{'OBJECTID': 178,
  'FID_BLD_part': 178,
  'KU_KOD': 608505,
  'ROOFFORM': 'Gable',
  'ROOFDIR': None,
  'RoofDirAdjust': 0,
  'BASEELEVATION': 266.04,
  'BLDGHEIGHT': 4.30500000000001,
  'EAVEHEIGHT': 2.5,
  'shapeName': 'myShape1',
  'RoofColor': '#FFFFFF',
  'WallColor': '#FFFFFF'}`

Then I run the script:
```
mod_parcel = pyprt.ModelGenerator(initial_geometries_from_set)
generated_parks = mod_parcel.generate_model(
    attrs, rpk, 'com.esri.prt.codecs.ColladaEncoder', encoder_options)
```

I am just getting a warning statement which is due to **None** value in field ROOFDIR.  
`[PRT] [2020-11-27 08:51:05] [warning] Encountered unknown scalar type for key ROOFDIR`

**Workflow 2 - generating output using CE**
I export the layer from AGOL to GDB on disk and this file I import to CE using Import FGDB. Then I apply the same rule package to the layer.

The output of two workflows is different (green buildings generated using Pyprt, red one RPK from CE).
![roofs](https://user-images.githubusercontent.com/37137459/100425617-d95adf80-308f-11eb-9fbd-94678b8723a7.PNG)

In the rule package roof orientation is based on the index of the first edge. So perhaps while reading geometry in Pyprt, the function defines the first edge differently.

**Comment by clechot** [comment]
Hi,

The None error is because you have to write `"None"` (as a string) in the attributes dictionary.
However, why is there this ROOFDIR attribute in the dictionary? It isn't listed by the `inspect_rpk` function, is it?

Concerning the roofs orientation issue, in CityEngine, what seed value is set?

**Comment by tramka** [comment]
Hi,

okay, I will change value to "None". Concerning ROOFDIR attribute, it is not important, I have just chosen it from attribute table in the query:

`blds_fset = blds_flayer.query(where='KU_KOD IN {}'.format(tuple(cadastral_areas)), 
                               out_fields='FID_BLD_part,KU_KOD,ROOFFORM,ROOFDIR,RoofDirAdjust,BASEELEVATION,BLDGHEIGHT,EAVEHEIGHT')`

It was created before (using 3D Basemaps Solution). In documentation there is a statement: 

> The attributes that control the roof form are building height, eave height, roof direction, and the type of roof are BLDGHEIGHT,EAVEHEIGHT, ROOFFORM, RoofDirAdjust. By editing these attributes, you can adjust your building models to better match the lidar data.

So it is completely fine that attribute ROOFDIR is not listed when executing `inspect_rpk` .

In the rule package I am not using seed anywhere. When I checked seed value in CityEngine, the value for random seed is set to 0.

**Comment by clechot** [comment]
Would it be possible for you to share the rule package with me?

**Comment by tramka** [comment]
Sure, I sent it to email.
