### ISSUE TITLE
Add support for macOS

### ISSUE THREAD

**Issue by mistafunk** [Esri/pyprt#9]
Ensure PyPRT builds and runs on macOS (10.15).

Tasks:
1. Get the cmake build system for the native part working on macOS (add compiler flags etc)
1. Get the unit tests passing
1. Get the examples working.

**Comment by davethejoy** [comment]
I concur! I volunteer to test! :)

**Comment by clechot** [comment]
(Part of internal ticket CE-7568.)

**Comment by mistafunk** [comment]
@davethejoy: i've produced a pre-release build of PyPRT 1.0 for macOS Catalina and Python 3.7, feel free to give it a spin :-)

[PyPRT-1.0.0-cp37-cp37m-macosx_10_15_x86_64.whl.zip](https://github.com/Esri/pyprt/files/4593213/PyPRT-1.0.0-cp37-cp37m-macosx_10_15_x86_64.whl.zip)

**Comment by davethejoy** [comment]
Rock on!!! Tx guys!

**Comment by davethejoy** [comment]
just checking if I am seeing the right thing: macosx is not yet part of conda right? at least we have the wheel file. :)

**Comment by clechot** [comment]
> just checking if I am seeing the right thing: macosx is not yet part of conda right? at least we have the wheel file. :)

That's right.

**Comment by mistafunk** [comment]
I created a conda pre-release package for macos: 
[pyprt-1.0.0-py37_0.tar.bz2.zip](https://github.com/Esri/pyprt/files/4597475/pyprt-1.0.0-py37_0.tar.bz2.zip)

Note: github doesn't allow the native conda tar.bz2 format, i had to zip it. please unzip first!

**Comment by mistafunk** [comment]
Merged to develop and scheduled for v1.1
